### ISSUE TITLE
Implement `Distance` operation

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/govec#17]
Calculates the distance between two vectors.

1. Calculate vector pointing from one to the other (vec1 - vec2)
2. Calculate the length of that vector
3. Return the value (always `float`)

Functions:
- `(v V2F[T]) Distance(v2 V2F[T]) float64`
- `(v V2F[T]) DistanceComp(x T, y T) float64`
- `(v V3F[T]) Distance(v2 V3F[T]) float64`
- `(v V3F[T]) DistanceComp(x T, y T, z T) float64`
- `(v V2I[T]) Distance(v2 V2I[T]) float64`
- `(v V2I[T]) DistanceComp(x T, y T) float64`
- `(v V3I[T]) Distance(v2 V3I[T]) float64`
- `(v V3I[T]) DistanceComp(x T, y T, z T) float64`

**Comment by sathuhebbar** [comment]
Hey, can I work on this? I have to implement this function for all 4 kinds of vectors right?

**Comment by Xkonti** [comment]
@sathuhebbar Sure you can. I added a list of all function variants in the description. You can look at `len.go` and `add.go` for reference. Thank you!

**Comment by sathuhebbar** [comment]
Thanks a lot. Here, `DistanceComp(x T, y T)` would be the distance between the vector `v` and `V2F[T]{x, y}` right?

**Comment by Xkonti** [comment]
Yes. Try to do operations on separate components instead of turning `x` and `y` into a vector. This way there will be one less operation for Go to perform, which will ever-so-slightly improve performance :)

**Comment by sathuhebbar** [comment]
Right. I have tried writing these functions in the new file distance.go. Would you please have a look?

Thank you.

**Comment by Xkonti** [comment]
Looks just right. Thank you!
