### ISSUE TITLE
Implement `IsZero` operation

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/govec#18]
Checks if the vector is a zero vector.

Example of usage:
```go
vec1 := V2F[float64]{X: 12, Y: 0}
result := vec1.IsZero()
// result is false
```

**Comment by sathuhebbar** [comment]
Hello, can I work on this issue?

Thank you.

**Comment by Xkonti** [comment]
Go ahead 👍

**Comment by sathuhebbar** [comment]
Cool! I've tried implementing it in this PR. Please have a look.

Thanks!

**Comment by Xkonti** [comment]
@sathuhebbar I can create an issue for adding tests for all operations that need them (most of them) if you want. I plan on looking into testing with [`testify` package](https://github.com/stretchr/testify) soon though. I don't have much experience with testing in Go, so if you can add some value/recommendations it would be much appreciated.

**Comment by Xkonti** [comment]
@sathuhebbar Here's the testing issue: https://github.com/Xkonti/govec/issues/34

**Comment by sathuhebbar** [comment]
Sure, will have a look at `testify`.
