### ISSUE TITLE
Implement `RotateDeg` operation

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/govec#23]
Rotates a vector by an angle specified in degrees.

Functions for integer vectors should return a float vector.

**Comment by KarolosLykos** [comment]
@Xkonti I would also like to work on this. Could you assign this to me?

**Comment by KarolosLykos** [comment]
I believe the implementation for 2D vectors is straightforward. However, for 3D vectors, I plan to introduce an additional argument in the 'rotateDeg' operation. This allows users to specify the rotation axis. Your input is valuable, so please feel free to share your thoughts!

**Comment by KarolosLykos** [comment]
@Xkonti Hello there! I hope you're doing well. I wanted to kindly ask if you could spare a moment to review my pull request (#50 ). I would greatly appreciate your feedback.

**Comment by Xkonti** [comment]
@KarolosLykos Looks good. I'm planning to focus on more advanced 3D vector math (rotations etc) after completing the 1.0. That will include concept like `plane`, `axis`, `quaternion`, but this simple approach here is fine for now.
